---
# Cloudflare API Token Secret
# This is used by Traefik for DNS-01 challenge (Let's Encrypt)
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: traefik
type: Opaque
stringData:
  token: <DNS SECRET HERE>