---
# HTTPRoute for flaresolverr.zinkzone.tech (Gateway API)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flaresolverr
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/hostname: flaresolverr.zinkzone.tech
spec:
  parentRefs:
    - name: homelab-gateway
      namespace: envoy-gateway-system
  hostnames:
    - flaresolverr.zinkzone.tech
  rules:
    - backendRefs:
        - name: flaresolverr
          port: 8191
