---
# External-DNS Service to create flaresolverr.zinkzone.tech DNS record
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr-external-dns
  namespace: traefik
  annotations:
    external-dns.alpha.kubernetes.io/hostname: flaresolverr.zinkzone.tech
spec:
  type: ExternalName
  externalName: traefik.zinkzone.tech
  ports:
    - port: 80
      protocol: TCP
      name: http
---
# Traefik IngressRoute for flaresolverr.zinkzone.tech
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: flaresolverr
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`flaresolverr.zinkzone.tech`)
      kind: Rule
      services:
        - name: flaresolverr
          port: 8191
  tls:
    certResolver: cloudflare
