---
# External-DNS Service to create radarr.zinkzone.tech DNS record
apiVersion: v1
kind: Service
metadata:
  name: radarr-external-dns
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/hostname: radarr.zinkzone.tech
spec:
  type: ExternalName
  externalName: traefik.zinkzone.tech
  ports:
    - port: 80
      protocol: TCP
      name: http
---
# Traefik IngressRoute for radarr.zinkzone.tech
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`radarr.zinkzone.tech`)
      kind: Rule
      services:
        - name: radarr
          port: 7878
  tls:
    certResolver: cloudflare
