---
# Sample PostgreSQL config.xml ConfigMap for Radarr
# Copy this file to postgres-config.secret.yaml and fill in the actual password
# Then apply with: kubectl apply -f postgres-config.secret.yaml
#
# Get password from: kubectl get secret -n pg-database cnpg-cluster-release-superuser -o jsonpath='{.data.password}' | base64 -d

apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-postgres-config
  namespace: media
data:
  config.xml: |
    <Config>
      <LogLevel>info</LogLevel>
      <UrlBase></UrlBase>
      <BindAddress>*</BindAddress>
      <Port>7878</Port>
      <SslPort>9898</SslPort>
      <EnableSsl>False</EnableSsl>
      <LaunchBrowser>False</LaunchBrowser>
      <ApiKey></ApiKey>
      <AuthenticationMethod>Forms</AuthenticationMethod>
      <AuthenticationRequired>DisabledForLocalAddresses</AuthenticationRequired>
      <Branch>master</Branch>
      <SslCertPath></SslCertPath>
      <SslCertPassword></SslCertPassword>
      <UpdateMechanism>Docker</UpdateMechanism>
      <InstanceName>Radarr</InstanceName>
      <PostgresUser>postgres</PostgresUser>
      <PostgresPassword><GET_FROM_cnpg-cluster-release-superuser_SECRET></PostgresPassword>
      <PostgresPort>5432</PostgresPort>
      <PostgresHost>cnpg-cluster-release-rw.pg-database.svc.cluster.local</PostgresHost>
      <PostgresMainDb>radarr-main</PostgresMainDb>
      <PostgresLogDb>radarr-log</PostgresLogDb>
    </Config>
