---
# External-DNS Service to create pdf.zinkzone.tech DNS record
apiVersion: v1
kind: Service
metadata:
  name: stirling-pdf-external-dns
  namespace: traefik
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pdf.zinkzone.tech
spec:
  type: ExternalName
  externalName: traefik.zinkzone.tech
  ports:
    - port: 80
      protocol: TCP
      name: http
---
# Traefik IngressRoute for pdf.zinkzone.tech
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pdf.zinkzone.tech`)
      kind: Rule
      services:
        - name: stirling-pdf
          port: 8080
  tls:
    certResolver: cloudflare
