---
# Documentation should be attached to each of the tasks.

- import_tasks: it-tools.yml

- import_tasks: stirling-pdf.yml

- import_tasks: mealie.yml

- import_tasks: netboot.yml

- import_tasks: pgadmin.yml

- import_tasks: portainer.yml

- import_tasks: tautulli.yml

# Changed to setup as it's expecting a traefik config if not prefixed
- import_tasks: setup-traefik.yml

- import_tasks: overseerr.yml