---
# External-DNS Service to create prowlarr.zinkzone.tech DNS record
apiVersion: v1
kind: Service
metadata:
  name: prowlarr-external-dns
  namespace: traefik
  annotations:
    external-dns.alpha.kubernetes.io/hostname: prowlarr.zinkzone.tech
spec:
  type: ExternalName
  externalName: traefik.zinkzone.tech
  ports:
    - port: 80
      protocol: TCP
      name: http
---
# Traefik IngressRoute for prowlarr.zinkzone.tech
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prowlarr.zinkzone.tech`)
      kind: Rule
      services:
        - name: prowlarr
          port: 9696
  tls:
    certResolver: cloudflare
