---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prowlarr-oci-helm
  namespace: flux-system
spec:
  type: oci
  interval: 30s
  url: oci://oci.trueforge.org/truecharts/prowlarr
