---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # Note: secret.secret.yaml is gitignored and must be applied manually
  # See README.md for secret setup instructions
  - meilisearch-deployment.yaml
  - chrome-deployment.yaml
  - karakeep-deployment.yaml
  - ingressroute.yaml
