---
# HTTPRoute for pgadmin.zinkzone.tech (Gateway API)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pgadmin
  namespace: pg-database
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pgadmin.zinkzone.tech
spec:
  parentRefs:
    - name: homelab-gateway
      namespace: envoy-gateway-system
  hostnames:
    - pgadmin.zinkzone.tech
  rules:
    - backendRefs:
        - name: pgadmin-release-pgadmin4
          port: 80
