---
# External-DNS Service to create pgadmin.zinkzone.tech DNS record
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-external-dns
  namespace: traefik
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pgadmin.zinkzone.tech
spec:
  type: ExternalName
  externalName: pgadmin.zinkzone.tech
  ports:
    - port: 80
      protocol: TCP
      name: http
---
# Traefik IngressRoute for pgadmin.zinkzone.tech
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pgadmin
  namespace: pg-database
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pgadmin.zinkzone.tech`)
      kind: Rule
      services:
        - name: pgadmin
          port: 80
  tls:
    certResolver: cloudflare
