---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin-release
  namespace: pg-database
spec:
  interval: 30m
  chart:
    spec:
      chart: pgadmin4
      sourceRef:
        kind: HelmRepository
        name: pgadmin-helm-repo
        namespace: flux-system
      interval: 12h
  values: {}
