---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-credentials
  namespace: pg-database
type: Opaque
stringData:
  PGADMIN_USERNAME: your-email@example.com
  PGADMIN_PASSWORD: your-secure-password-here
