---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin-release
  namespace: pg-database
spec:
  interval: 30m
  chart:
    spec:
      chart: pgadmin4
      sourceRef:
        kind: HelmRepository
        name: pgadmin-helm-repo
        namespace: flux-system
      interval: 12h
  values:
    # Load all environment variables from the secret
    envVarsFromSecrets:
      - pgadmin-credentials
    
    persistentVolume:
      enabled: true
      storageClass: "longhorn"
      size: "2Gi"
    
    startupProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 30
      successThreshold: 1

    # Resource management for pgAdmin
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
