---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin-release
  namespace: pg-database
spec:
  interval: 30m
  chart:
    spec:
      chart: pgadmin4
      sourceRef:
        kind: HelmRepository
        name: pgadmin-helm-repo
        namespace: flux-system
      interval: 12h
  values:
    startupProbe:
      httpGet:
        path: /
        port: http
      failureThreshold: 30
      periodSeconds: 2
    persistentVolume:
      enabled: true
      storageClass: "longhorn"
      size: "2Gi"
