---
# PiHole
# Documentation: https://github.com/CorentinTh/it-tools
# Purpose: Ad blocker at the network level

# This setup uses Docker so we need to ensure that it's running
- name: Ensure Docker is running
  service:
    name: docker
    state: started

- name: Setup 'Pihole' data directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
  with_items:
    - "{{ docker_data_pihole }}/etc"
    - "{{ docker_data_pihole }}/etc-dnsmasq.d"

- import_tasks: watchtower.yml

- import_tasks: pihole.yml
  when: extended_networking == 'false'

- import_tasks: app-server-pihole.yml
  when: extended_networking == 'true'

- import_tasks: dns-config.yml
  when: traefik_ip_address != ''