---
# Nebula Sync
# Documentation: https://www.howtogeek.com/why-run-2-pi-hole-instances-and-how-to-keep-them-synced/#:~:text=Most%20routers%20can%20use%20two,the%20other%20takes%20its%20place. 
# Purpose: To keep multiple pi-hole instances in sync with each other 

- name: Run 'Nebula Sync' - Docker Container
  docker_container:
    name: nebula-sync
    image: ghcr.io/lovelaze/nebula-sync:latest
    restart_policy: unless-stopped
    pull: true
    env:
      PRIMARY: "http://pihole|{{ pi_hole_password }}"
      REPLICAS: "{{ pihole_replica_csv }}"
      FULL_SYNC: "true"
      RUN_GRAVITY: "true"
      CRON: "0 * * * *"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
