---
# PiHole
# Documentation: https://github.com/CorentinTh/it-tools
# Purpose: Ad blocker at the network level

- name: Run 'Pi-Hole' - Docker Container
  docker_container:
    name: pihole
    image: pihole/pihole:latest
    restart_policy: unless-stopped
    privileged: true
    networks:
      - name: docker_ipvlan
        ipv4_address: "{{ pi_hole_container_ip }}"
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ docker_data_pihole }}/etc:/etc/pihole"
      - "{{ docker_data_pihole }}/etc-dnsmasq.d:/etc/dnsmasq.d"
      - "/etc/timezone:/etc/timezone:ro"
    env:
      TZ: "{{ time_zone }}"
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: "{{ pi_hole_password }}"
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'3
      FTLCONF_dns_listeningMode: "all"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.http.routers.pihole.entrypoints: "websecure,web"
      traefik.http.routers.pihole.tls: "true"
      traefik.http.routers.pihole.rule: "Host(`pihole.{{ domain_name }}`)"
      traefik.http.routers.pihole.service: "pihole"
      traefik.http.services.pihole.loadBalancer.server.port: "80"
