---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - grafana-secret.secret.yaml
  - kube-prometheus-stack-release.yaml
  - loki-release.yaml
  - promtail-release.yaml
  - httproute.yaml
