---
# Service pointing to external Node-RED
apiVersion: v1
kind: Service
metadata:
  name: nodered
  namespace: traefik
spec:
  type: ClusterIP
  clusterIP: None  # Headless service
  ports:
    - port: 1880
      targetPort: 1880
      protocol: TCP
      name: http
---
# Endpoints for Node-RED service
apiVersion: v1
kind: Endpoints
metadata:
  name: nodered
  namespace: traefik
subsets:
  - addresses:
      - ip: 192.168.101.3
    ports:
      - port: 1880
        name: http
---
# IngressRoute to route nodered.zinkzone.tech to Node-RED
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nodered
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nodered.zinkzone.tech`)
      kind: Rule
      services:
        - name: nodered
          port: 1880
  tls:
    certResolver: cloudflare
