---
# Service pointing to external Traccar
apiVersion: v1
kind: Service
metadata:
  name: traccar
  namespace: traefik
spec:
  type: ClusterIP
  clusterIP: None  # Headless service
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
---
# Endpoints for Traccar service
apiVersion: v1
kind: Endpoints
metadata:
  name: traccar
  namespace: traefik
subsets:
  - addresses:
      - ip: 192.168.101.10
    ports:
      - port: 8082
        name: http
---
# IngressRoute to route traccar.zinkzone.tech to Traccar
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traccar
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traccar.zinkzone.tech`)
      kind: Rule
      services:
        - name: traccar
          port: 8082
  tls:
    certResolver: cloudflare
