---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-cluster-release
  namespace: pg-database
spec:
  interval: 30m
  chart:
    spec:
      chart: cluster
      sourceRef:
        kind: HelmRepository
        name: cloud-native-postgres
        namespace: flux-system
      interval: 12h
  values:
    cluster:
      instances: 3

      storage:
        size: "4Gi"
        storageClass: longhorn
