---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-system-release
  namespace: pg-database
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cloud-native-postgres
        namespace: flux-system
      interval: 12h
  values: {}
