---
# HTTPRoute for authentik.zinkzone.tech (Gateway API)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: authentik
  namespace: auth
  annotations:
    external-dns.alpha.kubernetes.io/hostname: authentik.zinkzone.tech
spec:
  parentRefs:
    - name: homelab-gateway
      namespace: envoy-gateway-system
  hostnames:
    - authentik.zinkzone.tech
  rules:
    - backendRefs:
        - name: authentik-release-server
          port: 80
