---
# External-DNS Service to create authentik.zinkzone.tech DNS record
apiVersion: v1
kind: Service
metadata:
  name: authentik-external-dns
  namespace: traefik
  annotations:
    external-dns.alpha.kubernetes.io/hostname: authentik.zinkzone.tech
spec:
  type: ExternalName
  externalName: traefik.zinkzone.tech
  ports:
    - port: 80
      protocol: TCP
      name: http
---
# Traefik IngressRoute for authentik.zinkzone.tech
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik
  namespace: auth
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`authentik.zinkzone.tech`)
      kind: Rule
      services:
        - name: authentik-release-server
          port: 80
  tls:
    certResolver: cloudflare