docker_application_folder: /.docker

###########################################################################
# Plex Configuration
###########################################################################
docker_data_plex: "{{ docker_application_folder }}/plex"
plex_container_ip: 192.168.101.230
