---
# External-DNS Service to create sonarr.zinkzone.tech DNS record
apiVersion: v1
kind: Service
metadata:
  name: sonarr-external-dns
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/hostname: sonarr.zinkzone.tech
spec:
  type: ExternalName
  externalName: traefik.zinkzone.tech
  ports:
    - port: 80
      protocol: TCP
      name: http
---
# Traefik IngressRoute for sonarr.zinkzone.tech
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: media
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sonarr.zinkzone.tech`)
      kind: Rule
      services:
        - name: sonarr
          port: 8989
  tls:
    certResolver: cloudflare
