---
# Install common apps & software with apt
- import_tasks: apt.yml

# Ensure that ZWaveStick is properly setup for Home Assistant
#- import_tasks: setup-zstick.yml

- import_tasks: mount-backup-dir.yml

- import_tasks: traccar.yml