---
# HTTPRoute for overseerr.zinkzone.tech (Gateway API)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: overseerr
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/hostname: overseerr.zinkzone.tech
spec:
  parentRefs:
    - name: homelab-gateway
      namespace: envoy-gateway-system
  hostnames:
    - overseerr.zinkzone.tech
  rules:
    - backendRefs:
        - name: overseerr
          port: 5055
