---
# HTTPRoute for qbittorrent.zinkzone.tech (Gateway API)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: qbittorrent
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/hostname: qbittorrent.zinkzone.tech
spec:
  parentRefs:
    - name: homelab-gateway
      namespace: envoy-gateway-system
  hostnames:
    - qbittorrent.zinkzone.tech
  rules:
    - backendRefs:
        - name: qbittorrent
          port: 8080
