---
# External-DNS Service to create qbittorrent.zinkzone.tech DNS record
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-external-dns
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/hostname: qbittorrent.zinkzone.tech
spec:
  type: ExternalName
  externalName: traefik.zinkzone.tech
  ports:
    - port: 80
      protocol: TCP
      name: http
---
# Traefik IngressRoute for qbittorrent.zinkzone.tech
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`qbittorrent.zinkzone.tech`)
      kind: Rule
      services:
        - name: qbittorrent
          port: 8080
  tls:
    certResolver: cloudflare
