---
- hosts: plex
  vars_files:
    - "common.vars.yml"
    - "docker.vars.yml"
    - "plex.vars.yml"
    - "domain.vars.yml"
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ user_name }}"
          oh_my_zsh:
            theme: bureau
            plugins:
              - git
              - debian
              - docker
              - zsh-syntax-highlighting
              - zsh-autosuggestions
    - role: common
    - role: docker
    - role: plex
      tag:
        - plex
