---
- hosts: plex
  vars_files:
    - "common.vars.yml"
    - "docker.vars.yml"
    - "plex.vars.yml"
    - "domain.vars.yml"
  roles:
    - stat:
        path: "/home/{{ ansible-user }}/.oh-my-zsh"
        register: ohmyzsh_dir
    - role: mashimom.oh-my-zsh
      when: not ohmyzsh_dir.stat.exists
      ohmyzsh_theme: "bureau"
    - role: common
    - role: docker
    - role: plex
      tag:
        - plex
