---
- hosts: plex
  vars_files:
    - "common.vars.yml"
    - "docker.vars.yml"
    - "plex.vars.yml"
    - "domain.vars.yml"
  roles:
    - role: mashimom.oh-my-zsh
      ohmyzsh_theme: "bureau"
    - role: common
    - role: docker
    - role: plex
      tag:
        - plex
