---
- hosts: plex
  vars_files:
    - "common.vars.yml"
    - "docker.vars.yml"
    - "plex.vars.yml"
    - "domain.vars.yml"
  roles:
    - role: mashimom.oh-my-zsh
      when: not ansible_facts['user_dir'] is defined or not (ansible_facts['user_dir'] + '/.oh-my-zsh') | path_exists
      ohmyzsh_theme: "bureau"
    - role: common
    - role: docker
    - role: plex
      tag:
        - plex
