---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-downloads
spec:
  capacity:
    storage: 35Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-downloads-static
  mountOptions:
    - vers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: 192.168.1.197
    path: /volume1/Files/Torrent-Data
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-downloads-static
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
